apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvisadmin
spec:
  replicas: 1
  selector:
   matchLabels:
    app: mvisadmin
  template:
    metadata:
      labels:
        app: mvisadmin
    spec:
      containers:
      - name: mvisadmin
        image: cmadmin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
        env:
        - name: JAVA_OPTS
          value: -DTYPE=MVCM -Dlogging.console.enabled=true -DREDIS_HOST=redis
---
apiVersion: v1
kind: Service
metadata:
  name: mvisadmin
spec:
  type: LoadBalancer
  ports:
  - port: 7077
  selector:
    app: mvisadmin
